name: Tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Running tests
        run: pytest
